#!/usr/bin/env python3
import sys
import os

import helpers
from analyzer import Analyzer
from termcolor import colored

def main():
    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets word")

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    
    handle=sys.argv[1].strip("@")
    
    tweets=helpers.get_user_timeline(handle, 200)
    
    if(tweets!= None):
        for tweet in tweets:
            score = analyzer.analyze(tweet)
            if score > 0.0:
                print(colored("{} : {}".format(score, tweet), "green"))
            elif score < 0.0:
                print(colored("{} : {}".format(score, tweet), "red"))
            else:
                print(colored("{} : {}".format(score, tweet), "yellow"))
    else:
        print("Error, User invalid")
        exit(0)
            

if __name__ == "__main__":
    main()